# Generated by Django 5.1.2 on 2024-10-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_usd_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='usd_amount',
        ),
        migrations.AddField(
            model_name='paymentlink',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
