# Generated by Django 5.1.2 on 2024-10-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_usd_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='dispute_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='dispute_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='dispute_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_disputed',
            field=models.BooleanField(default=False),
        ),
    ]
