# Generated by Django 5.1.2 on 2024-10-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_payment_dispute_amount_payment_dispute_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentlink',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=10),
        ),
    ]
