services:
- type: web
  plan: free
  name: mysite
  runtime: python
  buildCommand: "./build.sh"
  startCommand: "python -m gunicorn dealflow.asgi:application -k uvicorn.workers.UvicornWorker"
  envVars:
  - key: WEB_CONCURRENCY
    value: 4
