# Generated by Django 5.1.2 on 2024-10-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_remove_paymentlink_expires_at_paymentlink_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='usd_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
